version: 0.0
os: linux
files:
  - source: /
    destination: /home/servicenow/rcservicenowapi.gate6.com/
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: servicenow
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: servicenow
