# Project information
site_name: App Connect for RingEX
site_url: https://github.com/ringcentral/rc-unified-crm-extension

# Repository
repo_url: https://github.com/ringcentral/rc-unified-crm-extension
repo_name: ringcentral/rc-unified-crm-extension
edit_uri: tree/master/docs
docs_dir: docs

theme:
  name: material
  logo: img/RingCentral_logo_color.png
  font:
    code: Roboto Mono
    text: Inter Tight
  features:
      - navigation.path
      - navigation.sections
      - navigation.expand
      - navigation.tabs
      - search.sharing
      - search.highlight
  palette:
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ringcentral
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ringcentraldevs
extra_css:
  - extra.css

#plugins:
#  pdf-export:
#    combined: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - mdx_include
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
       emoji_index: !!python/name:material.extensions.emoji.twemoji 
       emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "2023-2024 RingCentral, Inc. All rights reserved."

nav:
- 'Home': index.md
- 'Installation': getting-started.md
- 'Supported CRMs':
   - 'Overview': crm/index.md
   - 'Bullhorn': crm/bullhorn.md
   - 'Clio': crm/clio.md
   - 'Insightly': crm/insightly.md
   - 'Pipedrive': crm/pipedrive.md
   - 'Redtail CRM': crm/redtail.md
   - 'NetSuite': crm/netsuite.md
- 'User guide':
  - 'Accessing the extension': users/access.md
  - 'Making and receiving calls': users/making-calls.md
  - 'Logging calls': users/logging.md
  - 'Sending SMS': users/sms.md
  - 'Presence': users/presence.md
  - 'Settings': users/settings.md
- 'Developer guide':
  - 'Introduction': developers/index.md
  - 'Getting started': developers/getting-started.md
  - 'Technical overview': developers/adapter.md
  - 'Build and deployment': developers/deploy.md
  - 'Proprietary CRMs': developers/proprietary-crm.md
  - 'Adapter': 
    - 'Authorization': developers/auth.md
    - 'Manifest':
      - 'Manifest properties': developers/manifest.md
      - 'Customizing pages': developers/manifest-pages.md
      - 'Sample manifest': developers/manifest-sample.md
    - 'Server': 
      - 'Contact matching': developers/contact-matching.md
      - 'Logging phone calls': developers/logging-calls.md
      - 'Logging SMS': developers/logging-sms.md
      - 'Placeholder contacts': developers/placeholder-contacts.md
      - 'Viewing contacts and activities': developers/view-details.md
      - 'Welcome pages': developers/welcome-page.md
      - 'Returning errors': developers/errors.md
      - 'Building your own server': developers/advanced/openapi.md
    - 'Interfaces':
      - 'createCallLog': developers/interfaces/createCallLog.md
      - 'createMessageLog': developers/interfaces/createMessageLog.md
      - 'createContact': developers/interfaces/createContact.md
      - 'getAuthType': developers/interfaces/getAuthType.md
      - 'getCallLog': developers/interfaces/getCallLog.md
      - 'findContact': developers/interfaces/findContact.md
      - 'getOauthInfo': developers/interfaces/getOauthInfo.md
      - 'getUserInfo': developers/interfaces/getUserInfo.md
      - 'unAuthorize': developers/interfaces/unAuthorize.md
      - 'updateCallLog': developers/interfaces/updateCallLog.md
      - 'updateMessageLog': developers/interfaces/updateMessageLog.md

- 'Support':
  - 'Troubleshooting': support.md
  - 'Build a CRM adapter': build.md
  - 'Release notes': release-notes.md
