name: High Traffic Test
on:
    push:
        tags:
            - 'htt*'

jobs:
    server-test:
        runs-on: ubuntu-latest
        env:
            TEST_ENDPOINT_CREATE_USER: ${{ secrets.TEST_ENDPOINT_CREATE_USER }}
            TEST_ENDPOINT_GET_USER: ${{ secrets.TEST_ENDPOINT_GET_USER }}
            TEST_ENDPOINT_UPDATE_USER: ${{ secrets.TEST_ENDPOINT_UPDATE_USER }}
            TEST_ENDPOINT_DELETE_USER: ${{ secrets.TEST_ENDPOINT_DELETE_USER }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup node and npm
              uses: actions/setup-node@v2
              with:
                  node-version: '20'
                  registry-url: https://registry.npmjs.org/
            - run: echo "Start"
            - run: npm i
            - run: npm run htt
            - name: Coveralls
              uses: coverallsapp/github-action@v2